

import type { Metadata } from "next";
import "./globals.css";
import {
  NavigationMenuDemo
} from "../components/navigation_demo";
import * as React from "react";

export const metadata: Metadata = {
  title: "Mingda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="bg-black py-6 px-4 w-full flex justify-center">
           <NavigationMenuDemo></NavigationMenuDemo>
        </header>
        <main className="container mx-auto px-4 py-8">
          {children}
        </main>
        <footer className="py-4 text-center">
          <p>© 2025 Mingda. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}